# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'libraries/kunifiedpush': '@latest-kf6'
    'libraries/kweathercore': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'
 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kdbusaddons': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/kcrash': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
