# SPDX-FileCopyrightText: 2022 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

FROM python:3.10-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get update && apt-get -y install libgdal-dev
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app

EXPOSE 8000/tcp
CMD /app/entry.sh
