# SPDX-FileCopyrightText: 2022 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"

  aggregator:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
