# SPDX-FileCopyrightText: 2022 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"

  aggregator:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  httpd:
    image: httpd:2.4-bullseye
    depends_on:
      - aggregator
    restart: always
    volumes:
      - /srv/www/public-alerts/cap:/srv/www/public-alerts/cap
      - /srv/www/public-alerts/static:/srv/www/public-alerts/static
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "127.0.0.1:8000:80"
